# Generated by Django 6.0.2 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutme_birthday_aboutme_birthplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='team',
            field=models.URLField(blank=True),
        ),
    ]
